<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="P_VHMI" Id="{e08136d1-1ff9-41f3-90d9-ebf69fd94e3a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_VHMI
VAR
	fbModeSelect : FB_Mode;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbModeSelect(
	bMode := G_Modes.bAutoMode); ]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>